version: '3'
services:
  mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./scripts:/scripts
    entrypoint: /bin/bash /scripts/entrypoint.sh
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwiftTDS!
  mssql-2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - ./scripts:/scripts
    entrypoint: /bin/bash /scripts/entrypoint.sh
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwiftTDS!
