name: CI Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Swift Tests
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: StrongPassword123!
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: Run tests
        env:
          TDS_HOSTNAME: 127.0.0.1
          TDS_PORT: 1433
          TDS_DATABASE: master
          TDS_USERNAME: sa
          TDS_PASSWORD: StrongPassword123!
          TDS_ENABLE_SCHEMA_TESTS: 0
          TDS_ENABLE_ADMIN_TESTS: 0
          TDS_ENABLE_AGENT_TESTS: 0
        run: swift test
